/**
 * The eight people on the paywall's testimonial rail.
 *
 * WHY THEY EXIST. The screen this rail lives on used to promise features and
 * nothing else, and a feature list cannot answer the only question a new user
 * has at the paywall: who is this for, and is it for me. Eight use cases, each
 * said in one person's voice, answers it in the time it takes to scroll past.
 *
 * WHAT THE COPY MAY NOT DO. No superlatives, no star ratings, no "life
 * changing", no exclamation marks. Every quote names a specific way somebody
 * uses Katha (a campaign between D&D nights, the same chapter on the train home)
 * because a specific habit is recognisable and a compliment is not. The paywall
 * this replaced carried invented five-star reviews; these are illustrative use
 * cases written by the team, and they read as such.
 *
 * NO TAG (2026-09-12). Each card used to carry a use-case eyebrow above the
 * quote ("Plays himself in RPG stories"). It said the same thing the quote
 * underneath it already said, in the same card, one line earlier, and it cost
 * the rail the height that made the cards readable. The card is a photo, a
 * name and a quote; the use case is the quote's job.
 *
 * THE PORTRAITS. Provisional, generated by
 * `backend/scripts/generate-testimonial-portraits.ts` (OpenRouter,
 * `google/gemini-2.5-flash-image`) as explicitly generic people, never a
 * likeness of a real individual. The product lane replaces the files by name,
 * which is why the map below is a static `require` per slug: Metro resolves
 * `require` at build time, so a runtime-built path like
 * `require(\`../../assets/testimonials/${slug}.png\`)` does not bundle and the
 * rail would ship with eight empty circles.
 */
import type { ImageSourcePropType } from "react-native";

export type Testimonial = {
  /** Matches the file name in `expo/assets/testimonials/`. */
  slug: string;
  /** First name plus an initial. These are illustrative, not real customers. */
  name: string;
  quote: string;
  portrait: ImageSourcePropType;
};

export const TESTIMONIALS: readonly Testimonial[] = [
  {
    slug: "mateo-rpg",
    name: "Mateo R.",
    quote:
      "I drop my own character into a campaign between D&D nights and play out what happens off the table. The story remembers what he chose last chapter, so the next one starts from there.",
    portrait: require("../../assets/testimonials/mateo-rpg.png"),
  },
  {
    slug: "ana-bedtime",
    name: "Ana M.",
    quote:
      "Every night we make a new story with the kids in it and they pick who they want to be. By the third one my voice is gone, so I let the narration read it while I sit with them.",
    portrait: require("../../assets/testimonials/ana-bedtime.png"),
  },
  {
    slug: "dev-commute",
    name: "Dev S.",
    quote:
      "I listen on the train in and pick the same chapter back up on the way home. Forty minutes of standing still is now the part of the day I look forward to.",
    portrait: require("../../assets/testimonials/dev-commute.png"),
  },
  {
    slug: "chloe-fanfic",
    name: "Chloe B.",
    quote:
      "I draft here and then rewrite the lines that do not sound like me. Reimagine is the button I use most, usually three times on one paragraph until the voice lands.",
    portrait: require("../../assets/testimonials/chloe-fanfic.png"),
  },
  {
    slug: "marcus-dad",
    name: "Marcus T.",
    quote:
      "On Saturdays the three of us make a story and they decide what happens next at the end of every chapter. They argue about it for ten minutes, which is half the fun.",
    portrait: require("../../assets/testimonials/marcus-dad.png"),
  },
  {
    slug: "priya-bilingual",
    name: "Priya V.",
    quote:
      "I read a story in English and then read it again in Spanish to see how the sentences change. It holds my attention better than the textbook because I already want to know how it ends.",
    portrait: require("../../assets/testimonials/priya-bilingual.png"),
  },
  {
    slug: "ruth-memoir",
    name: "Ruth A.",
    quote:
      "I am turning the stories my mother told me into chapters for my grandchildren. Typing what I remember and reading it back as a proper chapter has kept me going for months.",
    portrait: require("../../assets/testimonials/ruth-memoir.png"),
  },
  {
    slug: "leo-worldbuilder",
    name: "Leo K.",
    quote:
      "I keep a cast of saved characters and pull them into whichever corner of the world I am writing that week. They look the same in every story, so the series reads like one place.",
    portrait: require("../../assets/testimonials/leo-worldbuilder.png"),
  },
];

export default TESTIMONIALS;
