/**
 * Auto-continue, written ahead of the reader.
 *
 * MEASURED, and the reason this exists: chapter one reaches its first token in
 * ~4.0s, a continuation in 7.0-7.9s, because a continuation's prompt carries
 * the previous chapters verbatim and chapter five carries four of them. In auto
 * mode nobody is being asked anything, so all of that used to be spent standing
 * on the last page of chapter N. Started when chapter N is persisted instead,
 * it runs underneath a chapter the reader still has in front of them.
 *
 * Every test here is a guard rather than a feature. The feature is one line:
 * start the next chapter early. The rest of the file is the set of things that
 * must never happen while doing it -- spending a stranger's credit, spending
 * two on one chapter, writing past a planned ending, or telling somebody a
 * chapter is on its way when the server refused to write it.
 */

import React from "react";
import { act, cleanup, render, waitFor } from "@testing-library/react-native";
import ChapterEnd from "@/components/reader/ChapterEnd";
import {
  __resetGenerationSessions,
  autoChapterToWriteAhead,
  clearAutoChapterFailure,
  hasGenerationForChapter,
  markAutoChapterFailed,
  startAutoChapterAhead,
  startChapterGeneration,
} from "@/lib/generation-session";
import { setViewerId } from "@/lib/ownership";
import type { Chapter, SeriesState, Story } from "@/types/domain";

jest.mock("@/lib/supabase", () => ({
  isSupabaseConfigured: false,
  SUPABASE_URL: "https://example.test",
  SUPABASE_ANON_KEY: "anon",
  supabase: { functions: { invoke: jest.fn() } },
}));
jest.mock("@/lib/session", () => ({ bootstrapUser: jest.fn() }));
jest.mock("@/lib/notifications", () => ({
  pushPermissionGranted: jest.fn().mockResolvedValue(false),
}));
// Only `continueStoryStreaming` is replaced, and only so that a refusal can be
// forced. Everything else on this module -- request ids, the offline
// continuation stub -- stays real, because the guards under test read them.
jest.mock("@/lib/api", () => ({
  ...jest.requireActual("@/lib/api"),
  continueStoryStreaming: jest.fn(),
}));

// eslint-disable-next-line import/first -- must be imported after the mock above.
import { continueStoryStreaming } from "@/lib/api";

const continueStreamMock = continueStoryStreaming as jest.MockedFunction<
  typeof continueStoryStreaming
>;

/** Enough credits for a continuation, and then some. */
const PLENTY = 10;

function makeSeriesState(): SeriesState {
  return {
    central_conflict: "A locked attic keeps its secret.",
    protagonist_want: "To hear the old fort song again.",
    relationship_state: "Aaji trusts her more each visit.",
    open_hooks: ["Follow the map fragment found under the floorboard."],
    resolved_hooks: [],
    promised_payoffs: [],
    world_facts: [],
    character_changes: [],
    next_chapter_pressure: "The storm is closing in on the fort.",
  };
}

function makeChapter(chapterNumber: number): Chapter {
  return {
    id: `chapter-${chapterNumber}`,
    storyId: "story-1",
    title: `Chapter ${chapterNumber}`,
    paragraphs: ["The attic door had not opened in years."],
    chapterNumber,
    chapterRole: chapterNumber === 1 ? "series_opening" : "mid_series",
    hookType: "unanswered_question",
    hookText: "The trunk's stuck page waited, unopened.",
    isPublished: true,
  };
}

function makeStory(overrides: Partial<Story> = {}): Story {
  return {
    id: "story-1",
    title: "The Old Fort",
    // "me" is what a story generated by this client is stamped with, and what
    // `isOwnStory` accepts without a viewer id.
    authorId: "me",
    genre: "adventure",
    storyMode: "series",
    storyFlow: "auto",
    plannedChapterCount: 3,
    beats: [
      "Chapter 1 beat: arrival at the fort.",
      "Chapter 2 beat: the locked attic.",
      "Ask Aaji to open the stuck page and share the old fort song.",
    ],
    seriesState: makeSeriesState(),
    synopsis: "A child rediscovers her grandmother's fort.",
    chapters: [makeChapter(1), makeChapter(2)],
    likes: 0,
    bookmarks: 0,
    views: 0,
    tags: [],
    publishedOffset: 0,
    isFeatured: false,
    language: "English",
    ...overrides,
  };
}

beforeEach(() => {
  // The offline stub, minus its 3-5 second sleep: these tests are about which
  // requests are made, never about what comes back.
  continueStreamMock.mockImplementation(() => new Promise(() => {}));
});

afterEach(() => {
  cleanup();
  __resetGenerationSessions();
  setViewerId(null);
  continueStreamMock.mockReset();
});

describe("autoChapterToWriteAhead", () => {
  it("starts the next chapter as soon as this one is persisted", () => {
    // Two chapters written of a planned three, nothing in flight: this is the
    // instant chapter 2 landed, minutes before the reader reaches its end.
    expect(autoChapterToWriteAhead(makeStory(), PLENTY)).toBe(3);
  });

  it("never fires in interactive mode", () => {
    // There is nothing to speculate on before the reader has picked a
    // direction, and a guess spends a credit on a chapter they did not choose.
    const story = makeStory({ storyFlow: "interactive" });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("never fires when the story says nothing about its flow", () => {
    // A legacy row, or a read that did not select the column. Absent is
    // interactive, exactly as the server clamps it.
    const story = makeStory({ storyFlow: undefined });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("never fires for a reader who does not own the story", () => {
    // `story_flow` rides on the row and public reads select it. Without the
    // ownership gate every reader of somebody else's public auto story would
    // spend a credit against a story they cannot continue -- no tap involved.
    const story = makeStory({ authorId: "someone-else" });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();

    // And it is the VIEWER's id that decides, not the string "me".
    setViewerId("someone-else");
    expect(autoChapterToWriteAhead(story, PLENTY)).toBe(3);
  });

  it("stops at the planned ending", () => {
    const story = makeStory({
      plannedChapterCount: 3,
      chapters: [makeChapter(1), makeChapter(2), makeChapter(3)],
    });
    // `continue-story` refuses a fourth chapter, so firing would reserve a
    // credit and hang a failure off a story that has properly ended.
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  /**
   * AUTO-CONTINUE MUST NOT AUTO-EXTEND. The safety line of the whole feature.
   *
   * A reader can now grow a finished story by tapping a direction chip at its
   * end, which raises `planned_chapter_count` and charges for the chapter.
   * This path must never do that on its own: it fires with nobody watching, so
   * an auto story that could extend itself would walk the reader's balance to
   * zero writing chapters past the plan they actually chose.
   *
   * A one-chapter story is the sharpest case -- extendable from the moment it
   * finishes, and one tap from becoming a fifteen-chapter bill.
   */
  it("never extends a story past its plan, however many credits are in hand", () => {
    const oneChapter = makeStory({
      plannedChapterCount: 1,
      chapters: [makeChapter(1)],
    });
    expect(autoChapterToWriteAhead(oneChapter, PLENTY)).toBeNull();

    // And nothing about the ceiling makes it fire either: a story mid-range is
    // just as finished at its own plan as a fifteen-chapter one is at 15.
    const extended = makeStory({
      plannedChapterCount: 4,
      chapters: [makeChapter(1), makeChapter(2), makeChapter(3), makeChapter(4)],
    });
    expect(autoChapterToWriteAhead(extended, PLENTY)).toBeNull();
  });

  /**
   * The stored plan is a RANGE. A story extended by hand to four chapters
   * stores 4, and the write-ahead has to keep writing to it -- the old
   * `3 | 7 | 15` membership test resolved 4 to the default 3 and stopped the
   * chain one chapter short of a chapter the reader had already paid to plan.
   */
  it("writes to a plan that is not one of the offered lengths", () => {
    const story = makeStory({
      plannedChapterCount: 4,
      chapters: [makeChapter(1), makeChapter(2), makeChapter(3)],
    });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBe(4);
  });

  it("treats an unknown planned count as the server's default of three", () => {
    const story = makeStory({
      plannedChapterCount: undefined,
      chapters: [makeChapter(1), makeChapter(2), makeChapter(3)],
    });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("never fires for a standalone", () => {
    const story = makeStory({
      storyMode: "standalone",
      chapters: [makeChapter(1)],
    });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("waits while anything else is being written into the story", () => {
    const story = makeStory();
    // A rewrite of chapter 2 is under way. Chapter 3 continues from chapter 2's
    // text, so starting it now would write a chapter out of prose that is
    // about to be replaced -- and two runs against one story race for the same
    // chapter number, which `continue-story` assigns from what is persisted.
    startChapterGeneration({
      story: makeStory({ chapters: [makeChapter(1)] }),
      nextChapterNumber: 2,
    });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("does not ask for the same chapter twice", () => {
    const story = makeStory();
    expect(startAutoChapterAhead({ story, credits: PLENTY })).not.toBeNull();
    // A second request reserves the same chapter, is refused 409 (KTH01), and
    // then becomes the newest session the reader follows -- a failure tail over
    // a chapter that is being written successfully.
    expect(startAutoChapterAhead({ story, credits: PLENTY })).toBeNull();
    expect(continueStreamMock).toHaveBeenCalledTimes(1);
  });

  it("does not fire when the balance cannot pay for it", () => {
    // The reader is about to be shown copy saying their next chapter is on its
    // way. With no credit the server answers 402 and that copy is a lie nobody
    // tapped for.
    expect(autoChapterToWriteAhead(makeStory(), 0)).toBeNull();
  });

  it("offers every direction and picks none of them itself", () => {
    const story = makeStory();
    const offered = [
      { id: "beat", prompt: "Ask Aaji to open the stuck page." },
      { id: "hook", prompt: "Follow the map fragment under the floorboard." },
    ];
    startAutoChapterAhead({ story, credits: PLENTY, resolveDirections: () => offered });
    // Signature: (storyId, requestId, handlers, isFinale, chapterNumber,
    //             direction, directionsOffered)
    const call = continueStreamMock.mock.calls[0];
    expect(call[4]).toBe(3);
    // Chapter 3 of a planned 3 is the finale, and the prompt has to say so.
    expect(call[3]).toBe(true);
    // NO direction is sent. Auto mode's choice belongs to the server, which
    // can read how the chapter ended; sending one here would be the client
    // deciding and the model rubber-stamping. A client sort is not a choice.
    expect(call[5]).toBeUndefined();
    expect(call[6]).toEqual(offered);
  });

  it("sends an empty offer rather than stalling when nothing is derivable", () => {
    startAutoChapterAhead({
      story: makeStory(),
      credits: PLENTY,
      resolveDirections: () => [],
    });
    const call = continueStreamMock.mock.calls[0];
    expect(call[5]).toBeUndefined();
    expect(call[6]).toEqual([]);
  });
});

/**
 * The chapter end is now the FALLBACK. It still fires for a reader whose next
 * chapter was never written ahead -- they were not in the reader when this one
 * landed, or the balance was short then -- and it must not fire for one whose
 * chapter is already sitting there.
 */
describe("the chapter-end fallback", () => {
  it("does not buy a second copy of a chapter already written ahead", async () => {
    const onContinue = jest.fn();
    const story = makeStory();
    startAutoChapterAhead({ story, credits: PLENTY });

    const { getByTestId } = await render(
      <ChapterEnd
        story={story}
        chapter={story.chapters[1]}
        onContinue={onContinue}
      />,
    );

    await waitFor(() => expect(getByTestId("chapter-end-auto")).toBeTruthy());
    expect(onContinue).not.toHaveBeenCalled();
    expect(continueStreamMock).toHaveBeenCalledTimes(1);
  });

  it("says a chapter is being written only while one actually is", async () => {
    const story = makeStory();
    startAutoChapterAhead({ story, credits: PLENTY });

    const { getByText } = await render(
      <ChapterEnd
        story={story}
        chapter={story.chapters[1]}
        onContinue={jest.fn()}
      />,
    );

    await waitFor(() =>
      expect(getByText(/Chapter 3 is being written/)).toBeTruthy()
    );
  });

  it("tells the reader the truth when the write-ahead was refused", async () => {
    // What a 402 looks like from here: the request was made minutes ago, off
    // screen, and came back refused. The reader arrives to a page that used to
    // claim their chapter was on its way.
    let refuse: (error: Error) => void = () => {};
    continueStreamMock.mockImplementation(
      () => new Promise((_resolve, reject) => { refuse = reject; }),
    );
    const story = makeStory();
    startAutoChapterAhead({ story, credits: PLENTY });

    const { getByTestId, getByText } = await render(
      <ChapterEnd
        story={story}
        chapter={story.chapters[1]}
        onContinue={jest.fn()}
      />,
    );
    await waitFor(() => expect(getByTestId("chapter-end-auto")).toBeTruthy());

    await act(async () => {
      refuse(new Error("Not enough credits to continue this story."));
    });

    expect(getByText("Chapter 3 didn't start")).toBeTruthy();
    // And a way out that is a tap, because re-firing a refusal automatically is
    // how one failure becomes a loop.
    expect(getByTestId("chapter-end-auto-retry")).toBeTruthy();
  });
});

/**
 * The chain runs to the plan or to the balance, whichever stops it first.
 *
 * A one-chapter-of-runway bound was built first and then removed as a product
 * decision (2026-09-11): auto mode means the reader asked not to be
 * interrupted, and stopping one chapter ahead still leaves them waiting at
 * every chapter after the first. These pin the two things that make the
 * unbounded chain safe.
 */
describe("the write-ahead chain", () => {
  it("keeps going chapter after chapter while the balance allows", async () => {
    const story = makeStory({ plannedChapterCount: 7 });
    // Nine credits, one per chapter: the chain is limited by the plan here,
    // not by the balance.
    expect(autoChapterToWriteAhead(story, 9)).toBe(story.chapters.length + 1);
    // And again from a story two chapters further on — the chain does not
    // stop at a fixed distance from where the reader is.
    const later = makeStory({
      plannedChapterCount: 7,
      chapters: [1, 2, 3, 4].map((n) => makeChapter(n)),
    });
    expect(autoChapterToWriteAhead(later, 9)).toBe(5);
  });

  it("stops at the last chapter the reader can actually afford", async () => {
    const plain = makeStory({ plannedChapterCount: 7 });
    expect(autoChapterToWriteAhead(plain, 1)).not.toBeNull();
    expect(autoChapterToWriteAhead(plain, 0)).toBeNull();
  });

  it("prices an illustrated chapter at two, not one", async () => {
    // Since migration 00077 a continuation is 1 credit for text and a second
    // for its art. Checking the text credit alone would fire the last chapter
    // with one credit in hand, take a 402 on a two-credit reservation, and
    // hang a failure off a story the reader was enjoying.
    const illustrated = makeStory({
      plannedChapterCount: 7,
      illustrateChapters: true,
    });
    expect(autoChapterToWriteAhead(illustrated, 2)).not.toBeNull();
    expect(autoChapterToWriteAhead(illustrated, 1)).toBeNull();
  });
});

/**
 * A failed chapter must not be bought again without a decision.
 *
 * `hasGenerationForChapter` reads the session store, and `pruneFinished` sweeps
 * it after 30 minutes — so a chapter that failed became eligible again the
 * moment its record aged out. The writer starts something else, comes back
 * later, and the chain fires a fresh paid request for the chapter that already
 * failed, with nothing on screen having asked.
 */
describe("a failed auto chapter", () => {
  it("is not re-bought after its session is swept", async () => {
    const story = makeStory({ plannedChapterCount: 7 });
    const session = startAutoChapterAhead({
      story,
      credits: PLENTY,
      resolveDirections: () => [],
    });
    expect(session).not.toBeNull();

    // The session ages out of the store entirely — `__resetGenerationSessions`
    // stands in for `pruneFinished`, which is not exported. The failure is then
    // re-asserted, which is the state the real sweep leaves behind: the record
    // is gone, the fact that this chapter failed is not.
    __resetGenerationSessions();
    markAutoChapterFailed(story.id, 3);

    // `hasGenerationForChapter` now knows nothing; the durable guard is the
    // only thing left, and it must hold.
    expect(hasGenerationForChapter(story.id, 3)).toBe(false);
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("runs again once the reader deliberately retries", () => {
    const story = makeStory({ plannedChapterCount: 7 });
    markAutoChapterFailed(story.id, 3);
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
    // "Retrying is a decision, and there is a button for it" — pressing it
    // lifts the bar, or the chapter would stay barred for the whole session.
    clearAutoChapterFailure(story.id, 3);
    expect(autoChapterToWriteAhead(story, PLENTY)).toBe(3);
  });
});

/**
 * The pre-bought run.
 *
 * Since migration 00087 an auto story does not buy its chapters one at a time.
 * When chapter one lands, `reserve_auto_chapter_run` reserves every remaining
 * planned chapter the balance can afford -- all of them, in one transaction --
 * and records the last one on `stories.auto_run_through_chapter`. The chain
 * reads that number instead of the live balance, and the two facts these tests
 * exist to pin are that it never writes past what was bought and never stops
 * short of it because some unrelated spend moved the balance.
 *
 * Everything above still applies to the chapters inside the run: ownership,
 * one request per chapter, never past the plan, never two at once, and the
 * durable failure bar. A pre-bought chapter is cheaper, not less guarded.
 */
describe("autoChapterToWriteAhead with a pre-bought run", () => {
  it("writes the chapters the run paid for, whatever the balance now says", () => {
    // Zero credits in hand and the run already bought through chapter three.
    // The old code refused here and left an auto story stalled on prose the
    // writer had already been charged for.
    const story = makeStory({
      plannedChapterCount: 3,
      autoRunThroughChapter: 3,
    });
    expect(autoChapterToWriteAhead(story, 0)).toBe(3);
  });

  it("stops at the end of the run rather than buying one more", () => {
    // The balance covers another chapter and the plan has room for it. Neither
    // is permission: auto mode buys once, at the start, and a chapter past the
    // run is a credit spent with nobody watching and no tap behind it.
    const story = makeStory({
      plannedChapterCount: 6,
      autoRunThroughChapter: 2,
    });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("stops immediately when the run bought nothing", () => {
    // A balance too short for even one chapter records the chapter BEFORE the
    // run began, which is one. That is a run of zero, and it is deliberately
    // distinguishable from the undefined below.
    const story = makeStory({
      plannedChapterCount: 3,
      autoRunThroughChapter: 1,
    });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("falls back to the balance for a story written before runs existed", () => {
    // `autoRunThroughChapter` is undefined on every story created before
    // migration 00087, and on any row read from a column list that predates
    // it. Those stories must keep continuing on the per-chapter path, or the
    // change would silently retire auto mode for everything already written.
    const legacy = makeStory({ plannedChapterCount: 3 });
    expect(legacy.autoRunThroughChapter).toBeUndefined();
    expect(autoChapterToWriteAhead(legacy, PLENTY)).toBe(3);
    expect(autoChapterToWriteAhead(legacy, 0)).toBeNull();
  });

  it("still refuses to write past the plan, run or no run", () => {
    // A run can never exceed the plan -- `reserve_auto_chapter_run` bounds it
    // there -- but the plan check must not become reachable only through the
    // balance. Extension is a deliberate tap, every time.
    const story = makeStory({
      plannedChapterCount: 2,
      autoRunThroughChapter: 9,
    });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("still refuses on somebody else's story", () => {
    setViewerId("someone-else");
    const story = makeStory({
      authorId: "the-author",
      plannedChapterCount: 3,
      autoRunThroughChapter: 3,
    });
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("still refuses a chapter that already failed", () => {
    const story = makeStory({
      plannedChapterCount: 3,
      autoRunThroughChapter: 3,
    });
    markAutoChapterFailed(story.id, 3);
    // Paid for is not the same as owed. A failed chapter of a run is refunded
    // by `refund_auto_chapter_run` along with the rest of it; re-firing it here
    // would be the client buying back what the server just gave away.
    expect(autoChapterToWriteAhead(story, PLENTY)).toBeNull();
  });

  it("still fires only one request per chapter", () => {
    const story = makeStory({
      plannedChapterCount: 3,
      autoRunThroughChapter: 3,
    });
    expect(startAutoChapterAhead({ story, credits: 0 })).not.toBeNull();
    expect(startAutoChapterAhead({ story, credits: 0 })).toBeNull();
    expect(continueStreamMock).toHaveBeenCalledTimes(1);
  });
});
