// Shared anti-slop lists for generated story narration.
// Kept in their own module so every prompt that bans them reads one list and
// they cannot drift apart.

export const BANNED_WORDS = [
  "delve",
  "tapestry",
  "testament",
  "pivotal",
  "underscore",
  "landscape",
  "foster",
  "beacon",
  "undeniably",
  "multifaceted",
  "nuanced",
  "intricate",
  "commendable",
  "meticulous",
  "endeavor",
  "realm",
  "paradigm",
  "synergy",
  "ecosystem",
  "framework",
  "robust",
  "streamline",
  "leverage",
  "harness",
  "utilize",
  "embark",
  "unravel",
  "comprehensive",
  "holistic",
  "unprecedented",
  "transformative",
  "groundbreaking",
  "innovative",
  "enhance",
  "crucial",
  "furthermore",
  "moreover",
  "consequently",
  "bustling",
  "labyrinth",
  "crucible",
  "ministrations",
] as const;

export const BANNED_PHRASES = [
  "it's not X — it's Y",
  "it is important to note",
  "it is worth mentioning",
  "in today's world",
  "at the end of the day",
  "one of the most",
  "when it comes to",
  "at its core",
  "no discussion would be complete without",
  "in this story",
  "overall",
  "in summary",
  "in conclusion",
  "little did they know",
  "stands as a testament",
  "plays a vital role",
  "rich cultural heritage",
  "enduring legacy",
  "a shiver ran down",
  "a wave of emotion washed over",
  "the weight of",
  "time seemed to stand still",
  "their eyes locked",
  "heart pounding in",
  "heart hammered against",
  "breath caught in",
  "let out a breath .* didn't know .* was holding",
  "couldn't help but",
  "voice barely above a whisper",
  "etched with",
  "gaze softened",
  "sent a chill through",
  "furrowed brow",
  "jaw tightened",
  "steeled themselves",
  "squared their shoulders",
  "eyes widened",
  "eyes sparkling",
  "knot in .* stomach",
  "pit in .* stomach",
  "air was thick with",
] as const;

export const BANNED_NAMES = [
  "Elara",
  "Seraphina",
  "Lysander",
  "Thorne",
  "Elowen",
  "Rowan",
  "Zephyr",
  "Isolde",
  "Caelum",
  "Evren",
] as const;
