// The generation deadline arithmetic, pinned.
//
// 2026-09-09, three findings on the same day:
//
//   1. A real chapter from the leading model takes 55-80s (measured against
//      production: 55.5s, 69.1s, 70s, 76.4s). The old 120s budget split its
//      84s paid window evenly across two models, 42s each, so every attempt
//      timed out before it had written anything - production recorded
//      `codes: [timeout, timeout, timeout, timeout]` with a healthy credential.
//   2. Every chapter is now generated by an ordinary blocking request, and the
//      Supabase gateway's request idle timeout is 150s on every plan. That is
//      the ceiling on the whole handler, not just the model call: past it the
//      caller gets a 504 and never sees the refund payload the handler built.
//      A blocking call that failed at 126.1s DID return its refund correctly,
//      which is the evidence that the shape below is survivable.
//   3. Gemini is disabled by `LLM_DISABLED_PROVIDERS`, so OpenRouter's paid
//      model is the only position expected to succeed.
//
// These tests are the arithmetic that must not regress.
import {
  assert,
  assertEquals,
} from "https://deno.land/std@0.224.0/assert/mod.ts";
import {
  EDGE_REQUEST_IDLE_TIMEOUT_MS,
  GENERATION_DEADLINE_MS,
  OPENROUTER_MODELS,
  OPENROUTER_PROBE_MS,
  openRouterPhaseDeadlines,
  PHASE_END_SHARE,
} from "./llm.ts";

/** The slowest chapter measured against production, 2026-09-09. */
const WORST_MEASURED_CHAPTER_MS = 76_400;

/**
 * What the handler spends outside the provider chain: the grounding pipeline
 * on the generation path (9s), plus auth, the credit reservation, persistence
 * and writing the response.
 */
const HANDLER_OVERHEAD_ALLOWANCE_MS = 15_000;

/** How much room is left before the gateway would answer 504 instead of us. */
const REQUIRED_MARGIN_MS = 10_000;

Deno.test("the whole blocking generation fits inside the gateway idle timeout", () => {
  assertEquals(EDGE_REQUEST_IDLE_TIMEOUT_MS, 150_000);
  const worstCase = GENERATION_DEADLINE_MS + HANDLER_OVERHEAD_ALLOWANCE_MS;
  assert(
    worstCase + REQUIRED_MARGIN_MS <= EDGE_REQUEST_IDLE_TIMEOUT_MS,
    `a ${GENERATION_DEADLINE_MS}ms chain plus ${HANDLER_OVERHEAD_ALLOWANCE_MS}ms of handler ` +
      `leaves only ${
        EDGE_REQUEST_IDLE_TIMEOUT_MS - worstCase
      }ms before the gateway ` +
      `answers 504 and swallows the refund payload`,
  );
});

Deno.test("the model that actually writes gets a chapter's worth of time", () => {
  const window = Math.floor(
    GENERATION_DEADLINE_MS * PHASE_END_SHARE.openrouter,
  );
  const deadlines = openRouterPhaseDeadlines(window, OPENROUTER_MODELS.length);
  assertEquals(deadlines.length, OPENROUTER_MODELS.length);
  const writer = deadlines[deadlines.length - 1];
  assert(
    writer >= WORST_MEASURED_CHAPTER_MS,
    `the writing model gets ${writer}ms against a ${WORST_MEASURED_CHAPTER_MS}ms chapter`,
  );
  // The last model owns the whole window: nothing is left unspendable.
  assertEquals(writer, window);
});

Deno.test("a model in front of the writer gets a probe, not a slice of the chapter", () => {
  const window = Math.floor(
    GENERATION_DEADLINE_MS * PHASE_END_SHARE.openrouter,
  );
  const deadlines = openRouterPhaseDeadlines(window, OPENROUTER_MODELS.length);
  for (let index = 0; index < deadlines.length - 1; index += 1) {
    const slice = index === 0
      ? deadlines[0]
      : deadlines[index] - deadlines[index - 1];
    // Long enough for a round trip and a `404`...
    assert(slice >= 5_000, `probe ${index} is only ${slice}ms`);
    // ...and nowhere near long enough to be mistaken for an attempt.
    assert(
      slice < WORST_MEASURED_CHAPTER_MS / 2,
      `probe ${index} holds ${slice}ms it cannot use`,
    );
  }
});

Deno.test("the tail phases are sized for a refusal, not a chapter, and are honest about it", () => {
  // Differences of the floored phase ends, exactly as `phaseDeadline` in
  // `llm.ts` computes them - flooring the difference of the shares instead
  // loses a millisecond to floating point and is not what runs.
  const end = (share: number) => Math.floor(GENERATION_DEADLINE_MS * share);
  const gemini = end(PHASE_END_SHARE.gemini) - end(PHASE_END_SHARE.openrouter);
  const free = end(PHASE_END_SHARE.openrouterFree) -
    end(PHASE_END_SHARE.gemini);
  for (const slice of [gemini, free]) {
    assert(slice >= 5_000, `a ${slice}ms slice cannot complete a round trip`);
  }
  // There is deliberately no claim that the tail is a second full attempt: a
  // 150s gateway cannot hold two 76s chapters. If this stops being true
  // because the transport changed, GENERATION_DEADLINE_MS is what to revisit.
  assert(
    gemini + free < WORST_MEASURED_CHAPTER_MS,
    "the tail now claims to be a second full attempt; re-read GENERATION_DEADLINE_MS",
  );
});

Deno.test("the paid phase is not split evenly, and a small window degrades to an equal share", () => {
  // 115s across two models: an 8s probe, then the writer with the whole window.
  assertEquals(openRouterPhaseDeadlines(115_000, 2), [8_000, 115_000]);
  // Probes accumulate; the last model still owns the window.
  assertEquals(openRouterPhaseDeadlines(100_000, 3), [8_000, 16_000, 100_000]);
  // A window too small to probe from falls back to equal slices.
  assertEquals(openRouterPhaseDeadlines(10_000, 2), [5_000, 10_000]);
  assertEquals(openRouterPhaseDeadlines(0, 2), [0, 0]);
  assertEquals(openRouterPhaseDeadlines(10_000, 0), []);
  assertEquals(OPENROUTER_PROBE_MS, 8_000);
});
