/**
 * Shared Story-world country contract.
 *
 * This table is deliberately checked in instead of asking ICU for display
 * names. Hermes does not implement `Intl.DisplayNames`, and host ICU versions
 * can rename a territory without a product change. Expo imports this pure
 * module directly; keep it free of Deno, React, and platform APIs.
 */
export type CountryWorld = {
  readonly label: string;
  readonly article?: "the";
  readonly aliases?: readonly string[];
};

/** The 249 assigned ISO 3166-1 alpha-2 country and territory codes. */
export const COUNTRY_WORLDS = {
  AD: { label: "Andorra" },
  AE: { label: "United Arab Emirates", article: "the" },
  AF: { label: "Afghanistan" },
  AG: { label: "Antigua and Barbuda" },
  AI: { label: "Anguilla" },
  AL: { label: "Albania" },
  AM: { label: "Armenia" },
  AO: { label: "Angola" },
  AQ: { label: "Antarctica" },
  AR: { label: "Argentina" },
  AS: { label: "American Samoa" },
  AT: { label: "Austria" },
  AU: { label: "Australia" },
  AW: { label: "Aruba" },
  AX: { label: "Åland Islands" },
  AZ: { label: "Azerbaijan" },
  BA: { label: "Bosnia and Herzegovina" },
  BB: { label: "Barbados" },
  BD: { label: "Bangladesh" },
  BE: { label: "Belgium" },
  BF: { label: "Burkina Faso" },
  BG: { label: "Bulgaria" },
  BH: { label: "Bahrain" },
  BI: { label: "Burundi" },
  BJ: { label: "Benin" },
  BL: { label: "Saint Barthélemy" },
  BM: { label: "Bermuda" },
  BN: { label: "Brunei" },
  BO: { label: "Bolivia" },
  BQ: { label: "Caribbean Netherlands", article: "the" },
  BR: { label: "Brazil" },
  BS: { label: "Bahamas", article: "the" },
  BT: { label: "Bhutan" },
  BV: { label: "Bouvet Island" },
  BW: { label: "Botswana" },
  BY: { label: "Belarus" },
  BZ: { label: "Belize" },
  CA: { label: "Canada" },
  CC: { label: "Cocos (Keeling) Islands" },
  CD: { label: "Democratic Republic of the Congo", article: "the" },
  CF: { label: "Central African Republic", article: "the" },
  CG: { label: "Republic of the Congo", article: "the" },
  CH: { label: "Switzerland" },
  CI: { label: "Côte d’Ivoire" },
  CK: { label: "Cook Islands", article: "the" },
  CL: { label: "Chile" },
  CM: { label: "Cameroon" },
  CN: { label: "China" },
  CO: { label: "Colombia" },
  CR: { label: "Costa Rica" },
  CU: { label: "Cuba" },
  CV: { label: "Cape Verde" },
  CW: { label: "Curaçao" },
  CX: { label: "Christmas Island" },
  CY: { label: "Cyprus" },
  CZ: { label: "Czechia", aliases: ["Czech Republic"] },
  DE: { label: "Germany", aliases: ["Deutschland"] },
  DJ: { label: "Djibouti" },
  DK: { label: "Denmark" },
  DM: { label: "Dominica" },
  DO: { label: "Dominican Republic" },
  DZ: { label: "Algeria" },
  EC: { label: "Ecuador" },
  EE: { label: "Estonia" },
  EG: { label: "Egypt" },
  EH: { label: "Western Sahara" },
  ER: { label: "Eritrea" },
  ES: { label: "Spain" },
  ET: { label: "Ethiopia" },
  FI: { label: "Finland" },
  FJ: { label: "Fiji" },
  FK: { label: "Falkland Islands", article: "the" },
  FM: { label: "Micronesia" },
  FO: { label: "Faroe Islands", article: "the" },
  FR: { label: "France" },
  GA: { label: "Gabon" },
  GB: {
    label: "United Kingdom",
    article: "the",
    aliases: ["UK", "Britain", "Great Britain", "England"],
  },
  GD: { label: "Grenada" },
  GE: { label: "Georgia" },
  GF: { label: "French Guiana" },
  GG: { label: "Guernsey" },
  GH: { label: "Ghana" },
  GI: { label: "Gibraltar" },
  GL: { label: "Greenland" },
  GM: { label: "Gambia", article: "the" },
  GN: { label: "Guinea" },
  GP: { label: "Guadeloupe" },
  GQ: { label: "Equatorial Guinea" },
  GR: { label: "Greece" },
  GS: { label: "South Georgia and the South Sandwich Islands" },
  GT: { label: "Guatemala" },
  GU: { label: "Guam" },
  GW: { label: "Guinea-Bissau" },
  GY: { label: "Guyana" },
  HK: { label: "Hong Kong" },
  HM: { label: "Heard Island and McDonald Islands" },
  HN: { label: "Honduras" },
  HR: { label: "Croatia" },
  HT: { label: "Haiti" },
  HU: { label: "Hungary" },
  ID: { label: "Indonesia" },
  IE: { label: "Ireland" },
  IL: { label: "Israel" },
  IM: { label: "Isle of Man" },
  IN: { label: "India" },
  IO: { label: "British Indian Ocean Territory" },
  IQ: { label: "Iraq" },
  IR: { label: "Iran" },
  IS: { label: "Iceland" },
  IT: { label: "Italy" },
  JE: { label: "Jersey" },
  JM: { label: "Jamaica" },
  JO: { label: "Jordan" },
  JP: { label: "Japan" },
  KE: { label: "Kenya" },
  KG: { label: "Kyrgyzstan" },
  KH: { label: "Cambodia" },
  KI: { label: "Kiribati" },
  KM: { label: "Comoros", article: "the" },
  KN: { label: "Saint Kitts and Nevis" },
  KP: { label: "North Korea" },
  KR: { label: "South Korea" },
  KW: { label: "Kuwait" },
  KY: { label: "Cayman Islands", article: "the" },
  KZ: { label: "Kazakhstan" },
  LA: { label: "Laos" },
  LB: { label: "Lebanon" },
  LC: { label: "Saint Lucia" },
  LI: { label: "Liechtenstein" },
  LK: { label: "Sri Lanka" },
  LR: { label: "Liberia" },
  LS: { label: "Lesotho" },
  LT: { label: "Lithuania" },
  LU: { label: "Luxembourg" },
  LV: { label: "Latvia" },
  LY: { label: "Libya" },
  MA: { label: "Morocco" },
  MC: { label: "Monaco" },
  MD: { label: "Moldova" },
  ME: { label: "Montenegro" },
  MF: { label: "Saint Martin" },
  MG: { label: "Madagascar" },
  MH: { label: "Marshall Islands", article: "the" },
  MK: { label: "North Macedonia", aliases: ["Macedonia"] },
  ML: { label: "Mali" },
  MM: { label: "Myanmar", aliases: ["Burma"] },
  MN: { label: "Mongolia" },
  MO: { label: "Macao" },
  MP: { label: "Northern Mariana Islands", article: "the" },
  MQ: { label: "Martinique" },
  MR: { label: "Mauritania" },
  MS: { label: "Montserrat" },
  MT: { label: "Malta" },
  MU: { label: "Mauritius" },
  MV: { label: "Maldives", article: "the" },
  MW: { label: "Malawi" },
  MX: { label: "Mexico" },
  MY: { label: "Malaysia" },
  MZ: { label: "Mozambique" },
  NA: { label: "Namibia" },
  NC: { label: "New Caledonia" },
  NE: { label: "Niger" },
  NF: { label: "Norfolk Island" },
  NG: { label: "Nigeria" },
  NI: { label: "Nicaragua" },
  NL: { label: "Netherlands", article: "the", aliases: ["Holland"] },
  NO: { label: "Norway" },
  NP: { label: "Nepal" },
  NR: { label: "Nauru" },
  NU: { label: "Niue" },
  NZ: { label: "New Zealand" },
  OM: { label: "Oman" },
  PA: { label: "Panama" },
  PE: { label: "Peru" },
  PF: { label: "French Polynesia" },
  PG: { label: "Papua New Guinea" },
  PH: { label: "Philippines", article: "the" },
  PK: { label: "Pakistan" },
  PL: { label: "Poland" },
  PM: { label: "Saint Pierre and Miquelon" },
  PN: { label: "Pitcairn Islands", article: "the" },
  PR: { label: "Puerto Rico" },
  PS: { label: "Palestinian Territories" },
  PT: { label: "Portugal" },
  PW: { label: "Palau" },
  PY: { label: "Paraguay" },
  QA: { label: "Qatar" },
  RE: { label: "Réunion" },
  RO: { label: "Romania" },
  RS: { label: "Serbia" },
  RU: { label: "Russia" },
  RW: { label: "Rwanda" },
  SA: { label: "Saudi Arabia" },
  SB: { label: "Solomon Islands", article: "the" },
  SC: { label: "Seychelles", article: "the" },
  SD: { label: "Sudan" },
  SE: { label: "Sweden" },
  SG: { label: "Singapore" },
  SH: { label: "Saint Helena" },
  SI: { label: "Slovenia" },
  SJ: { label: "Svalbard and Jan Mayen" },
  SK: { label: "Slovakia" },
  SL: { label: "Sierra Leone" },
  SM: { label: "San Marino" },
  SN: { label: "Senegal" },
  SO: { label: "Somalia" },
  SR: { label: "Suriname" },
  SS: { label: "South Sudan" },
  ST: { label: "São Tomé and Príncipe" },
  SV: { label: "El Salvador" },
  SX: { label: "Sint Maarten" },
  SY: { label: "Syria" },
  SZ: { label: "Eswatini", aliases: ["Swaziland"] },
  TC: { label: "Turks and Caicos Islands", article: "the" },
  TD: { label: "Chad" },
  TF: { label: "French Southern Territories", article: "the" },
  TG: { label: "Togo" },
  TH: { label: "Thailand" },
  TJ: { label: "Tajikistan" },
  TK: { label: "Tokelau" },
  TL: { label: "Timor-Leste" },
  TM: { label: "Turkmenistan" },
  TN: { label: "Tunisia" },
  TO: { label: "Tonga" },
  TR: { label: "Türkiye", aliases: ["Turkey"] },
  TT: { label: "Trinidad and Tobago" },
  TV: { label: "Tuvalu" },
  TW: { label: "Taiwan" },
  TZ: { label: "Tanzania" },
  UA: { label: "Ukraine" },
  UG: { label: "Uganda" },
  UM: { label: "U.S. Outlying Islands", article: "the" },
  US: {
    label: "United States",
    article: "the",
    aliases: ["USA", "US", "America"],
  },
  UY: { label: "Uruguay" },
  UZ: { label: "Uzbekistan" },
  VA: { label: "Vatican City" },
  VC: { label: "Saint Vincent and the Grenadines" },
  VE: { label: "Venezuela" },
  VG: { label: "British Virgin Islands", article: "the" },
  VI: { label: "U.S. Virgin Islands", article: "the" },
  VN: { label: "Vietnam" },
  VU: { label: "Vanuatu" },
  WF: { label: "Wallis and Futuna" },
  WS: { label: "Samoa" },
  YE: { label: "Yemen" },
  YT: { label: "Mayotte" },
  ZA: { label: "South Africa" },
  ZM: { label: "Zambia" },
  ZW: { label: "Zimbabwe" },
} as const satisfies Record<string, CountryWorld>;

export type CountryCode = keyof typeof COUNTRY_WORLDS;
export const COUNTRY_CODES: readonly CountryCode[] = Object.freeze(
  Object.keys(COUNTRY_WORLDS),
) as CountryCode[];

export function storyWorldPromptName(code: CountryCode): string {
  const country: CountryWorld = COUNTRY_WORLDS[code];
  return country.article
    ? `${country.article} ${country.label}`
    : country.label;
}

export function matchesCountryWorld(
  country: CountryWorld,
  query: string,
): boolean {
  const needle = query.trim().toLocaleLowerCase();
  if (!needle) return true;
  return [country.label, ...(country.aliases ?? [])]
    .some((value) => value.toLocaleLowerCase().includes(needle));
}
