[project]
id = "iafeuxgoiknncgyjmugd"

[api]
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"

[auth.external.google]
enabled = false

[auth.external.apple]
enabled = false

[storage]
file_size_limit = "10MB"

[functions.adapty-webhook]
verify_jwt = false
